app:
  external:
    api:
      ip2country: 
        url: "https://api.ip2country.info/ip"
      restcountries:
        url: "https://restcountries.eu/rest/v2/alpha"
      exchangeratesapi:
        url: "https://api.exchangeratesapi.io/latest"
  currency:
    symbol: "USD"